### ISSUE TITLE
Deprecation status on Ansible Galaxy

### ISSUE THREAD

**Issue by C0rn3j** [gantsign/ansible_role_antigen#79]
https://galaxy.ansible.com/gantsign/antigen
https://galaxy.ansible.com/gantsign/antigen_bundles

I see these two project have a huge red "Deprecated" tag on them, why is that? I was not able to find an an answer in the readme or existing issues.

**Comment by freemanjp** [comment]
Hi @C0rn3j, as of Aug 2022, the last release of Antigen was 4.5 years ago [v2.2.3](https://github.com/zsh-users/antigen/releases/tag/v2.2.3). This role actually uses version [v2.0.2](https://github.com/zsh-users/antigen/releases/tag/v2.0.2) (over 5 years old), due to issues later versions had with some Oh My Zsh plugins. So, I think it's fair to say Antigen is not maintained at this point.

I deprecated my Antigen Ansible roles as I don't think it's responsible to encourage people to adopt unmaintained software.

I'm still using my roles, so they'll continue to be maintained for the time being. But I've been looking to replace Antigen with another Zsh plugin manager. I found [zplug](https://github.com/zplug/zplug) easy to use, but a bit slow on shell initialization. I'm probably going to switch to [zimfw](https://github.com/zimfw/zimfw), it's very fast but it comes at the cost of being a bit harder to configure. I don't have any current plans to write another Ansible role for zimfw.

**Comment by C0rn3j** [comment]
Thanks for the writeup, it does indeed seem like [the project is dead](https://github.com/zsh-users/antigen/issues/725).

I would keep this issue open/pinned and possibly add a warning to the top of the readme, since it doesn't look like this is going to get resolved.

**Comment by freemanjp** [comment]
A deprecation notice has been added to the `README.md` of both roles.
